# Generated by Django 4.1.7 on 2023-03-10 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='restaurant_name')),
                ('code_postal', models.CharField(max_length=8, null=True)),
                ('email_or_phone', models.CharField(max_length=30, null=True, unique=True)),
                ('speciality', models.CharField(max_length=50, null=True)),
                ('highlight', models.BooleanField(verbose_name='restaurant highlight')),
                ('opening_time', models.TimeField(null=True)),
                ('closing_time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6)),
                ('code_wifi', models.CharField(max_length=30, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restuarant_city', to='masters.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_country', to='masters.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
