# Generated by Django 4.1.7 on 2023-03-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email_or_phone',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
