# Generated by Django 4.1.7 on 2023-03-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_email_or_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
