# Generated by Django 4.1.7 on 2023-03-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='country_id',
            new_name='country',
        ),
    ]
