version: '3'
services:


  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network
    restart: always

  backend:
    build: .
    command: bash -c "python manage.py migrate; python manage.py runserver"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - db_network
    restart: always


networks:
  db_network:
    driver: bridge

volumes:
  pgdata: