# Generated by Django 4.1.7 on 2023-03-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
    ]
