# Generated by Django 4.1.7 on 2023-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_or_phone',
            field=models.CharField(max_length=30),
        ),
    ]
