# Generated by Django 4.1.7 on 2023-03-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0005_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_or_phone',
            field=models.CharField(max_length=100),
        ),
    ]
