# Generated by Django 4.1.7 on 2023-03-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userrole_restaurant_alter_userprofile_email_or_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
