# Generated by Django 4.1.7 on 2023-03-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
